version: "3.8"

services:
  build:
    image: devcontainer-ngdotnet:build
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NODE_VERSION=16
        - GITHUB_TOKEN=${GITHUB_TOKEN}
    
  create:
    image: devcontainer-ngdotnet:build
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NODE_VERSION: 16
        GITHUB_TOKEN: ${GITHUB_TOKEN}
    command: ./create.sh
    volumes:
      - ${PWD}:/scripts/output