name: Build

on:
  push:
    branches:
      - "*"
      - "!release/latest"

jobs:
  check_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: satackey/action-docker-layer-caching@v0.0.11
        continue-on-error: true

      - name: Build image
        run: docker-compose build
