name: Build

on:
  push:
    branches:
      - "*"
      - "!release/latest"

jobs:
  check_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build image
        run: docker-compose build
